fix(ci/cd): added scacap/action-surefire-report@v1

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -52,14 +52,16 @@ jobs:
         run: mvn -B package --file pom.xml
       - name: Test with Maven
         run: mvn clean test
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: Test Results
-          path: ${{ github.workspace }}/target/surefire-reports/*.xml
-          reporter: java-junit
-
+#      - name: Test Report
+#        uses: dorny/test-reporter@v1
+#        if: success() || failure()
+#        with:
+#          name: Test Results
+#          path: ${{ github.workspace }}/target/surefire-reports/*.xml
+#          reporter: java-junit
+      - name: Publish Test Report
+        if: ${{ always() }}
+        uses: scacap/action-surefire-report@v1
       - name: Upload target folder
         uses: actions/upload-artifact@v2
         with:
